# Instruct vulkan loader to ignore Nvidia manifest to stop Nvidia discovery.
#   Mitigation: When the vulkan loader initializes and queries the nvidia GPU, it forces it
#   into D0 mode as the Nvidia driver does not allow for information to be gathered in D3COLD.
VK_LOADER_DRIVERS_DISABLE=nvidia_icd.json

# Instruct OpenGL/EGL to not scan vendor directory.
__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json
